# Generated by Django 5.2.4 on 2025-07-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='img',
            field=models.ImageField(default='main/static/images/profile_pic.jpg', null=True, upload_to='main/static/images/'),
        ),
    ]
