# Generated by Django 5.1.4 on 2025-03-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_task_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.guest'),
        ),
    ]
