# Generated by Django 5.1.4 on 2025-03-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
    ]
