# Generated by Django 5.2.4 on 2025-07-12 19:34

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_guest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='img',
            field=models.ImageField(default='main/static/images/profile_pic.jpg', null=True, storage=storages.backends.s3.S3Storage(), upload_to='static/images/'),
        ),
    ]
