# Generated by Django 5.2.4 on 2025-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_guest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
