# Generated by Django 5.2.4 on 2025-07-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_guest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='img',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
