# Generated by Django 5.2.4 on 2025-07-03 17:25

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_guest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='img',
            field=models.ImageField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='profile_images/'),
        ),
    ]
