# Generated by Django 5.2.4 on 2025-07-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_guest_img_alter_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
