# Generated by Django 5.2.4 on 2025-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_guest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='img',
            field=models.ImageField(null=True, upload_to='main/static/images/'),
        ),
    ]
